version: "3"

services:
    # GraphQL server 01
    node-app:
        build:
            context: ./node-app
        container_name: node-app
        # ports:
        #   - 3001:4000
        # env_file: graphql_var.env
        # depends_on:
        # - payment-api
        restart: always

    # Nginx reverse proxy
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - 80:80
            # - 443:443 #ssl
        depends_on:
            - node-app

        restart: always
        volumes:
            - ./data/cahe:/data/nginx/cache

        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
